### ISSUE TITLE
fix: quantity cannot be negative

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#13]
![negative](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/6ca98bd2-09bf-40a9-98c4-079f594603f6)

while searching for a product in the stock and decreasing its quantity using "-"
- it should reduce only to 0 and not less than it
- decreasing button should get disabled after that

**Comment by Quarcoo-arc** [comment]
@codewithsonyy I could work on this issue.

**Comment by codewithsonyy** [comment]
> @codewithsonyy I could work on this issue.

yes please :)
