### ISSUE TITLE
Add Contributing.md file 

### ISSUE THREAD

**Issue by aarjun8060** [codewithsonyy/inventory-management2.0#20]
Add a contributing file in the repo.

->How to make a pull request to this repo

->How to clone this repo 

above both questions, is defined clearly

why is this issue?
because many contributors facing issues to setup repo  in the local system

**Comment by Quarcoo-arc** [comment]
Should we create a separate file for helping others **get started** or we should modify what currently is in the README.md file?

**Comment by Quarcoo-arc** [comment]
> Should we create a separate file for helping others **get started** or we should modify what currently is in the README.md file?

I think I was confused between `Getting Started` and `Contributing`. I get it now. 
I can work on this issue.

**Comment by codewithsonyy** [comment]
> > Should we create a separate file for helping others **get started** or we should modify what currently is in the README.md file?
> 
> I think I was confused between `Getting Started` and `Contributing`. I get it now. I can work on this issue.

I think for now readme file is enough. Just leave it @Quarcoo-arc  and @aarjun8060

**Comment by Quarcoo-arc** [comment]
> > > Should we create a separate file for helping others **get started** or we should modify what currently is in the README.md file?
> > 
> > 
> > I think I was confused between `Getting Started` and `Contributing`. I get it now. I can work on this issue.
> 
> I think for now readme file is enough. Just leave it @Quarcoo-arc and @aarjun8060

Most certainly.
Could I modify the readme file to make it more intuitive? @codewithsonyy

**Comment by codewithsonyy** [comment]
> > > > Should we create a separate file for helping others **get started** or we should modify what currently is in the README.md file?
> > > 
> > > 
> > > I think I was confused between `Getting Started` and `Contributing`. I get it now. I can work on this issue.
> > 
> > I think for now readme file is enough. Just leave it @Quarcoo-arc and @aarjun8060
> 
> Most certainly.
> Could I modify the readme file to make it more intuitive? @codewithsonyy 

 Sure! @Quarcoo-arc give a pull request when you are done!
