### ISSUE TITLE
Signup - Page improvement

### ISSUE THREAD

**Issue by shivang21007** [codewithsonyy/inventory-management2.0#22]
- Like the login page I want to improve Sign-up Page also .
- like this - 
![image](https://github.com/codewithsonyy/inventory-management2.0/assets/98748694/9c677dfb-0df0-4f2d-8b3b-a3197de782da)

- **Please Assign me this issue under Hacktoberfest :)**

**Comment by codewithsonyy** [comment]
@shivang21007 yes sure! Please keep it responsive if possible
