### ISSUE TITLE
Make display cards mobile responsive using tailwind

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#3]
![tab](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/a4f2f310-422b-4fac-9746-a714c8a8e664)

**Comment by kritisoni19** [comment]
Hi, I followed the same setup process for the frontend part but I am a little confused about the backend can you share the code for the .env file also? right now when I am trying to register, it is showing user already exists. it would be great if you could help

**Comment by codewithsonyy** [comment]
> Hi, I followed the same setup process for the frontend part but I am a little confused about the backend can you share the code for the .env file also? right now when I am trying to register, it is showing user already exists. it would be great if you could help

![Screenshot (320)](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/4073ea54-8d7e-4176-a4f4-0a31ae7b2990)


You can just login: soni@gmail.com
password: soni1234

**Comment by codewithsonyy** [comment]
If any other problem please let me know! I will try to solve it @kritisoni19

**Comment by kritisoni19** [comment]
Hi @codewithsonyy, I copied the same code for .env file and used the same credentials as you gave to me but, the page is showing credentials are invalid.
![Screenshot 2023-10-18 154914](https://github.com/codewithsonyy/inventory-management2.0/assets/120715673/adcf19f9-fb55-495e-ba46-6811d54604cd)

**Comment by codewithsonyy** [comment]
@kritisoni19 
well that login works/exists only on my database not yours. Sorry I shared that login before. 
- You have to set up your own mongodb url and have to register first as a new user then login
- make sure you are connected to db else it will throw error on console

**Comment by aarjun8060** [comment]
Can you assign this to me ?

**Comment by codewithsonyy** [comment]
> Can you assign this to me ?

yes sure! please go ahead.

**Comment by aarjun8060** [comment]
I am sharing you message on LinkedIn regarding this issue please check it out
