### ISSUE TITLE
fix the search result responsiveness using tailwind

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#4]
![fix](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/d8ca4702-66c2-40c2-ae3a-6f28913e3ca8)

**Comment by Davidthecode** [comment]
hey @codewithsonyy, i could work on this issue

**Comment by codewithsonyy** [comment]
> hey @codewithsonyy, i could work on this issue

Yes please! do let me know if any problem

**Comment by Davidthecode** [comment]
hey @codewithsonyy i'm having issues signing in to the site. it says - Invalid credentials, and i have an account

**Comment by codewithsonyy** [comment]
> hey @codewithsonyy i'm having issues signing in to the site. it says - Invalid credentials, and i have an account

I created new issue( #9 ) for this. if you are not connected to mongodb it will show "Invalid credentials" or "user already exits"
- Just directly put connection string  in the db\dbConnect.js mongoose.connect("your-connection-string") 
<br/>
In case process.env is not working

**Comment by aarjun8060** [comment]
Can you assign this to me ?

**Comment by codewithsonyy** [comment]
> Can you assign this to me ?

are you working on it @aarjun8060 ? If yes then you have to sync all new changes in your repo & system and then work on new branch!

**Comment by aarjun8060** [comment]
yes I am working

**Comment by aarjun8060** [comment]
creating a PR . Please check it and tell me if any issue.

**Comment by codewithsonyy** [comment]
> creating a PR . Please check it and tell me if any issue.

No issue! Thanks a ton @aarjun8060  : )
