### ISSUE TITLE
feat: add a delete button/icon and make api route to delete 

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#5]
Make an api route for deleting product from database
[first successful pr will be gifted Rs 100 if you have phone pe and from india]

<img width="821" alt="delete" src="https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/56d80486-d0d3-499c-a840-ce3bd85a16d6">

**Comment by aarjun8060** [comment]
Hi @codewithsonyy , I want to try this feature issue. I am new to source contribution. Can you assign this issue to me?

**Comment by codewithsonyy** [comment]
@aarjun8060  Most welcome! If any problem let me know.

**Comment by aarjun8060** [comment]
@codewithsonyy  Hi, I am creating a PR . check it out . if any issue regarding this then tell me
