### ISSUE TITLE
feat: update quantity with price accordingly

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#6]
![Screenshot (318)](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/58d90935-93ea-411c-8756-7e7190115530)

desc:
when we search and update quanity with + and - 
<br/>
it only updates quanity in mongodb and reflects back the changes
- I want the price to decrease and increase accordingly.
- For that a column price/product be made
- total price should be calculate quantity* price/product

gift:
As I cant pay in dollar since I am unemployed myself ,
anyone using phonepe/upi can be gifted Rs 200 for first successful pr.
connect on linkedin!

Happy coding :)

**Comment by Quarcoo-arc** [comment]
Happy to help.

@codewithsonyy Kindly confirm if there is a backend for this application. If yes, what was used to build it?

**Comment by Quarcoo-arc** [comment]
I think I got it... Both frontend and backend were developed using Next.js

**Comment by codewithsonyy** [comment]
> Happy to help.
> 
> @codewithsonyy Kindly confirm if there is a backend for this application. If yes, what was used to build it?

Thanks for taking interest :)
yes @Quarcoo-arc  both frontend and backend using next.js!
well mongodb atlas is used for backend.
This is my .env.local file 
![Screenshot (320)](https://github.com/codewithsonyy/inventory-management2.0/assets/114895266/cdee2e04-80ab-4f5d-ad18-03bf4017517d)

**Comment by Quarcoo-arc** [comment]
Thanks @codewithsonyy.

I would like to contribute this feature.

**Comment by aarjun8060** [comment]
can you assign this feat to me ?

Can you explain more these three line
I want the price to decrease and increase accordingly.
For that a column price/product be made
total price should be calculate quantity* price/product

**Comment by Quarcoo-arc** [comment]
> can you assign this feat to me ?
> 
> Can you explain more these three line I want the price to decrease and increase accordingly. For that a column price/product be made total price should be calculate quantity* price/product

I'm currently working on it. Should be done soon.
