### ISSUE TITLE
wrong 500 error handling in the frontend

### ISSUE THREAD

**Issue by codewithsonyy** [codewithsonyy/inventory-management2.0#9]
problem:-
error 500 is not handled well in frontend.
- sign in page
It simply shows alert message "Invalid Credentials" for network issue or other issue
- sign up page
It simply shows alert message "User already exists. Please login!" 
- In short
When you are not connected to mongodb
it will show "User already exists. Please login!"  on sign up and "Invalid Credentials"  during login

**Comment by Quarcoo-arc** [comment]
@codewithsonyy I can work on this issue as well

**Comment by codewithsonyy** [comment]
> @codewithsonyy I can work on this issue as well

You have to sync all the new data in your forked repo so that no merge conflict arises. If any new issue arises coz of past merges let me know. I have not yet tested project after changes
happy coding :)
